export function createGeneralCustomerData() {
  return {
    profissao: 'Engenheiro',
    telefoneEmergencia: '(11) 91234-5678',
    tratamentoEsteticoAnterior: true,
    toxinaBotulinica: false,
    toxinaBotulinicaRegiao: undefined,
    preenchimento: true,
    preenchimentoRegiao: 'Rosto',
    preenchimentoProduto: 'Ácido Hialurônico',
    fiosDeSustentacao: false,
    fiosDeSustentacaoRegiao: undefined,
    fiosDeSustentacaoProduto: undefined,
    liftCirurgico: false,
    liftRegiao: undefined,
    liftProduto: undefined,
    peelingQuimico: true,
    peelingQuimicoRegiao: 'Rosto',
    peelingQuimicoProduto: 'Ácido Retinoico',
    laser: true,
    laserRegiao: 'Braços',
    laserProduto: 'Laser CO2',
    trabalhoExposto: false,
    trabalhoExpostoRegiao: undefined,
    trabalhoExpostoProduto: undefined,
    usaMedicamento: true,
    usaMedicamentoQual: 'Anti-inflamatório',
    alergia: false,
    gestanteOuLactante: false,
    intoleranciaLactose: true,
    diabetes: false,
    roacutam: false,
    fumante: false,
    disturbioCirculatorio: false,
    epilepsia: false,
    cicloMenstrualRegular: true,
    funcionamentoIntestinalRegular: true,
    tratamentoMedico: true,
    tratamentoMedicoDetalhes: 'Hipertensão controlada',
    cirurgiaRecente: false,
    cirurgiaRecenteDetalhes: undefined,
    problemasDePele: true,
    problemasDePeleDetalhes: 'Dermatite',
    proteseCorporalOuFacial: false,
    proteseCorporalOuFacialDetalhes: undefined,
    gestantes: false,
    gestantesDetalhes: undefined,
    tumor: false,
    tumorDetalhes: undefined,
    problemaOrtopedico: false,
    problemaOrtopedicoDetalhes: undefined,
    utilizandoAcidos: true,
    utilizandoAcidosDetalhes: 'Uso de ácido retinoico',
    observacaoProblema: 'Observações adicionais sobre o cliente.',
    created_at: new Date(),
  }
}
